# Generated by Django 5.2.9 on 2026-03-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('teacher', 'Преподаватель'), ('dean', 'Деканат'), ('umu', 'УМУ'), ('admin', 'Админ')], default='teacher', max_length=32),
        ),
    ]
