# Generated by Django 5.2.9 on 2026-01-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_email_verification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("teacher", "Преподаватель"),
                    ("program_leader", "Руководитель программы"),
                    ("dean", "Декан"),
                    ("umu", "УМУ"),
                    ("admin", "Админ"),
                ],
                default="teacher",
                max_length=32,
            ),
        ),
    ]
