# Generated by Django 5.2.9 on 2026-01-07 00:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_user_role"),
        ("accounts", "0003_alter_user_role_alter_user_username_and_more"),
    ]

    operations = []
