# Generated by Django 5.2.9 on 2026-01-10 14:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_merge_0003_conflict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(code='invalid', message='Enter a valid username. This value may contain only letters, numbers, and @/./+/-/_ characters.', regex='^[0-9A-Za-z@.+_\\-ЁёА-Яа-я]+\\Z')], verbose_name='username'),
        ),
    ]
