# Generated by Django 5.2.9 on 2026-01-24 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('teacher', 'Преподаватель'), ('program_leader', 'Руководитель программы'), ('dean', 'Деканат'), ('umu', 'УМУ'), ('admin', 'Админ')], default='teacher', max_length=32),
        ),
    ]
