# Generated by Django 5.2.9 on 2026-01-29 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_verified',
        ),
        migrations.DeleteModel(
            name='EmailVerification',
        ),
    ]
