# Generated by Django 5.2.9 on 2026-01-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="available_languages",
            field=models.CharField(
                help_text="Доступные языки, например: ru,kz,en",
                max_length=50,
            ),
        ),
    ]
