# Generated by Django 5.2.9 on 2025-12-08 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=50)),
                ('academic_year', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('submitted_dean', 'Отправлено декану'), ('approved_dean', 'Утверждено деканом'), ('submitted_umu', 'Отправлено в УМУ'), ('approved_umu', 'Утверждено УМУ'), ('rejected', 'Отклонено')], default='draft', max_length=32)),
                ('total_weeks', models.PositiveIntegerField(default=15)),
                ('main_language', models.CharField(default='ru', max_length=5)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='syllabi_pdfs/')),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabi', to='catalog.course')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabi', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SyllabusTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField()),
                ('is_included', models.BooleanField(default=True)),
                ('custom_title', models.CharField(blank=True, max_length=255)),
                ('custom_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabus_topics', to='syllabi.syllabus')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.topic')),
            ],
            options={
                'ordering': ['week_number'],
            },
        ),
    ]
