# Generated by Django 5.2.9 on 2026-01-29 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabi', '0004_syllabusrevision'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabus',
            name='ai_feedback',
            field=models.TextField(blank=True, help_text='Замечания от ИИ проверки'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('ai_check', 'На проверке ИИ'), ('correction', 'На доработке'), ('review_dean', 'Согласование: Декан'), ('review_umu', 'Согласование: УМУ'), ('approved', 'Утвержден'), ('rejected', 'Отклонено (Архив)')], default='draft', max_length=32),
        ),
    ]
