# Generated by Django 5.2.9 on 2026-01-22 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabi', '0004_syllabusrevision'),
        ('workflow', '0002_alter_syllabusstatuslog_changed_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyllabusAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('details_updated', 'Обновлены разделы'), ('topics_updated', 'Обновлены темы'), ('topics_cleared', 'Темы очищены'), ('pdf_uploaded', 'Загружен PDF'), ('status_changed', 'Сменен статус')], max_length=32)),
                ('message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='syllabi.syllabus')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
